// Actions for smart pilot manager.
export const GET_AP = 'GET_AP'
export const GET_AP_SUCCESS = 'GET_AP_SUCCESS'

// Load AP settings for a selected ad group.
export const GET_AP_AD_GROUP = 'GET_AP_AD_GROUP'
export const GET_AP_AD_GROUP_SUCCESS = 'GET_AP_AD_GROUP_SUCCESS'

export const GET_AP_SKUS = 'GET_AP_SKUS'
export const GET_AP_SKUS_SUCCESS = 'GET_AP_SKUS_SUCCESS'

export const GET_AP_SPSD_CAMPAIGNS = 'GET_AP_SPSD_CAMPAIGNS'
export const GET_AP_SPSD_CAMPAIGNS_SUCCESS = 'GET_AP_SPSD_CAMPAIGNS_SUCCESS'

export const GET_AP_SB_CAMPAIGNS = 'GET_AP_SB_CAMPAIGNS'
export const GET_AP_SB_CAMPAIGNS_SUCCESS = 'GET_AP_SB_CAMPAIGNS_SUCCESS'

export const GET_AP_TEST_RESULTS = 'GET_AP_TEST_RESULTS'
export const GET_AP_TEST_RESULTS_SUCCESS = 'GET_AP_TEST_RESULTS_SUCCESS'

export const GET_AP_CAMPAIGNS_TO_APPLY = 'GET_AP_CAMPAIGNS_TO_APPLY'
export const GET_AP_CAMPAIGNS_TO_APPLY_SUCCESS = 'GET_AP_CAMPAIGNS_TO_APPLY_SUCCESS'

export const SAVE_AP = 'SAVE_AP'
export const SAVE_AP_SUCCESS = 'SAVE_AP_SUCCESS'

export const SAVE_AP_TEMPLATE = 'SAVE_AP_TEMPLATE'
export const SAVE_AP_TEMPLATE_SUCCESS = 'SAVE_AP_TEMPLATE_SUCCESS'

export const GET_AP_TEMPLATES = 'GET_AP_TEMPLATES'
export const GET_AP_TEMPLATES_SUCCESS = 'GET_AP_TEMPLATES_SUCCESS'

export const TURN_AP_BULK = 'TURN_AP_BULK'
export const TURN_AP_BULK_SUCCESS = 'TURN_AP_BULK_SUCCESS'

export const APPLY_TEMPLATE_BULK = 'APPLY_TEMPLATE_BULK'
export const APPLY_TEMPLATE_BULK_SUCCESS = 'APPLY_TEMPLATE_BULK_SUCCESS'
