export const LOGIN_START   = 'LOGIN_START'
export const LOGIN_SUCCEED = 'LOGIN_SUCCEED'
export const LOGIN_FAILED  = 'LOGIN_FAILED'

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'

export const CHANGE_USER_INFO_SUCCEED = 'CHANGE_USER_INFO_SUCCEED'
export const SAVE_NOTIFICATION_SUCCEED = 'SAVE_NOTIFICATION_SUCCEED'
export const SAVE_UNIVERSAL_SUCCEED = 'SAVE_UNIVERSAL_SUCCEED'

export const CHECK_AUTH_SUCCEED = 'CHECK_AUTH_SUCCEED'
export const CHECK_AUTH_FAILED = 'CHECK_AUTH_FAILED'

export const SIGNUP_BASIC_START = 'SIGNUP_BASIC_START'
export const SIGNUP_BASIC_SUCCEED = 'SIGNUP_BASIC_SUCCEED'
export const SIGNUP_BASIC_FAILED = 'SIGNUP_BASIC_FAILED'

export const SP_CODE_START = 'SP_CODE_START'
export const SP_CODE_SUCCEED = 'SP_CODE_SUCCEED'
export const SP_CODE_FAILED = 'SP_CODE_FAILED'

export const AD_CODE_START = 'AD_CODE_START'
export const AD_CODE_SUCCEED = 'AD_CODE_SUCCEED'
export const AD_CODE_FAILED = 'AD_CODE_FAILED'

export const SIGNUP_SUCCEED = 'SIGNUP_SUCCEED'
