export const GET_DETAILS_START = 'GET_DETAILS_START'
export const GET_DETAILS_SUCCEED = 'GET_DETAILS_SUCCEED'

export const CHANGE_NEGATIVE_KEYWORD_STATE_START = 'CHANGE_NEGATIVE_KEYWORD_STATE_START'
export const CHANGE_NEGATIVE_KEYWORD_STATE_SUCCEED = 'CHANGE_NEGATIVE_KEYWORD_STATE_SUCCEED'

export const CHANGE_NEGATIVE_TARGET_STATE_START = 'CHANGE_NEGATIVE_TARGET_STATE_START'
export const CHANGE_NEGATIVE_TARGET_STATE_SUCCEED = 'CHANGE_NEGATIVE_TARGET_STATE_SUCCEED'

export const UPDATE_NAME_START = 'UPDATE_NAME_START'
export const UPDATE_NAME_SUCCEED = 'UPDATE_NAME_SUCCEED'
export const UPDATE_NAME_FAIL = 'UPDATE_NAME_FAIL'

export const UPDATE_ACOS_START = 'UPDATE_ACOS_START'
export const UPDATE_ACOS_SUCCEED = 'UPDATE_ACOS_SUCCEED'
export const UPDATE_ACOS_FAIL = 'UPDATE_ACOS_FAIL'

export const UPDATE_PORTFOLIO_START = 'UPDATE_PORTFOLIO_START'
export const UPDATE_PORTFOLIO_SUCCEED = 'UPDATE_PORTFOLIO_SUCCEED'
export const UPDATE_PORTFOLIO_FAIL = 'UPDATE_PORTFOLIO_FAIL'

export const UPDATE_BIDDING_START = 'UPDATE_BIDDING_START'
export const UPDATE_BIDDING_SUCCEED = 'UPDATE_BIDDING_SUCCEED'
export const UPDATE_BIDDING_FAIL = 'UPDATE_BIDDING_FAIL'

export const GET_SKU_DATA_START = 'GET_SKU_DATA_START'
export const GET_SKU_DATA_SUCCEED = 'GET_SKU_DATA_SUCCEED'

export const CHANGE_SKU_STATE_START = 'CHANGE_SKU_STATE_START'
export const CHANGE_SKU_STATE_SUCCEED = 'CHANGE_SKU_STATE_SUCCEED'

export const GET_ST_DATA_START = 'GET_ST_DATA_START'
export const GET_ST_DATA_SUCCEED = 'GET_ST_DATA_SUCCEED'
export const GET_ST_DATA_FAIL = 'GET_ST_DATA_FAIL'

export const GET_NEGATIVE_KW_DATA_START = 'GET_NEGATIVE_KW_DATA_START'
export const GET_NEGATIVE_KW_DATA_SUCCEED = 'GET_NEGATIVE_KW_DATA_SUCCEED'
export const GET_NEGATIVE_KW_DATA_FAIL = 'GET_NEGATIVE_KW_DATA_FAIL'

export const GET_BID_DATA_START = 'GET_BID_DATA_START'
export const GET_BID_DATA_SUCCEED = 'GET_BID_DATA_SUCCEED'
export const GET_BID_DATA_FAIL = 'GET_BID_DATA_FAIL'

export const CHANGE_KEYWORD_BID_START = 'CHANGE_KEYWORD_BID_START'
export const CHANGE_KEYWORD_BID_SUCCEED = 'CHANGE_KEYWORD_BID_SUCCEED'
export const CHANGE_KEYWORD_BID_FAIL = 'CHANGE_KEYWORD_BID_FAIL'

export const CHANGE_KEYWORD_STATE_START = 'CHANGE_KEYWORD_STATE_START'
export const CHANGE_KEYWORD_STATE_SUCCEED = 'CHANGE_KEYWORD_STATE_SUCCEED'

export const GET_BID_TARGET_DATA_START = 'GET_BID_TARGET_DATA_START'
export const GET_BID_TARGET_DATA_SUCCEED = 'GET_BID_TARGET_DATA_SUCCEED'
export const GET_BID_TARGET_DATA_FAIL = 'GET_BID_TARGET_DATA_FAIL'

export const CHANGE_TARGET_START = 'CHANGE_TARGET_START'
export const CHANGE_TARGET_SUCCEED = 'CHANGE_TARGET_SUCCEED'
export const CHANGE_TARGET_FAIL = 'CHANGE_TARGET_FAIL'

export const GET_NEGATIVE_WORD_DATA_START = 'GET_NEGATIVE_WORD_DATA_START'
export const GET_NEGATIVE_WORD_DATA_SUCCEED = 'GET_NEGATIVE_WORD_DATA_SUCCEED'
export const GET_NEGATIVE_WORD_DATA_FAIL = 'GET_NEGATIVE_WORD_DATA_FAIL'

export const GET_NEGATIVE_TARGET_DATA_START = 'GET_NEGATIVE_TARGET_DATA_START'
export const GET_NEGATIVE_TARGET_DATA_SUCCEED = 'GET_NEGATIVE_TARGET_DATA_SUCCEED'
export const GET_NEGATIVE_TARGET_DATA_FAIL = 'GET_NEGATIVE_TARGET_DATA_FAIL'

export const GET_PLACEMENT_DATA_START = 'GET_PLACEMENT_DATA_START'
export const GET_PLACEMENT_DATA_SUCCEED = 'GET_PLACEMENT_DATA_SUCCEED'
export const GET_PLACEMENT_DATA_FAIL = 'GET_PLACEMENT_DATA_FAIL'

export const UPDATE_PLACEMENT_BID_START = 'UPDATE_PLACEMENT_BID_START'
export const UPDATE_PLACEMENT_BID_SUCCEED = 'UPDATE_PLACEMENT_BID_SUCCEED'
export const UPDATE_PLACEMENT_BID_FAIL = 'UPDATE_PLACEMENT_BID_FAIL'
