export const MIN_DASHBOARD_TABLE = 'MIN_DASHBOARD_TABLE'
export const MAX_DASHBOARD_TABLE = 'MAX_DASHBOARD_TABLE'

export const GET_DASHBOARD_SALES_STATS_START = 'GET_DASHBOARD_SALES_STATS_START'
export const GET_DASHBOARD_SALES_STATS_SUCCEED = 'GET_DASHBOARD_SALES_STATS_SUCCEED'

export const GET_DASHBOARD_STATS_START = 'GET_DASHBOARD_STATS_START'
export const GET_DASHBOARD_STATS_SUCCEED = 'GET_DASHBOARD_STATS_SUCCEED'
